url: http://www.librenms.org

# Site settings
title: LibreNMS
description: LibreNMS is an autodiscovering PHP/MySQL-based network monitoring system.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: da223a
  secondary: c91028
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/LibreNMS
  - title: comment
    url: https://discord.com/invite/librenms
  - title: reddit
    url: https://www.reddit.com/r/LibreNMS/
  - title: facebook-official
    url: https://www.facebook.com/LibreNMS
#  - title: google-plus
#    url: https://plus.google.com/u/1/communities/111170344284862070465
  - title: github
    url: https://github.com/librenms/librenms
#  - title: apple
#    url: https://t.libren.ms/iphone
#  - title: android
#    url: https://t.libren.ms/android

# Build settings
permalink: pretty
plugins:
  - jekyll-redirect-from
